// Generated by gencpp from file ropigo/SimpleWrite.msg
// DO NOT EDIT!


#ifndef ROPIGO_MESSAGE_SIMPLEWRITE_H
#define ROPIGO_MESSAGE_SIMPLEWRITE_H

#include <ros/service_traits.h>


#include <ropigo/SimpleWriteRequest.h>
#include <ropigo/SimpleWriteResponse.h>


namespace ropigo
{

struct SimpleWrite
{

typedef SimpleWriteRequest Request;
typedef SimpleWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SimpleWrite
} // namespace ropigo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ropigo::SimpleWrite > {
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::ropigo::SimpleWrite&) { return value(); }
};

template<>
struct DataType< ::ropigo::SimpleWrite > {
  static const char* value()
  {
    return "ropigo/SimpleWrite";
  }

  static const char* value(const ::ropigo::SimpleWrite&) { return value(); }
};


// service_traits::MD5Sum< ::ropigo::SimpleWriteRequest> should match 
// service_traits::MD5Sum< ::ropigo::SimpleWrite > 
template<>
struct MD5Sum< ::ropigo::SimpleWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ropigo::SimpleWrite >::value();
  }
  static const char* value(const ::ropigo::SimpleWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ropigo::SimpleWriteRequest> should match 
// service_traits::DataType< ::ropigo::SimpleWrite > 
template<>
struct DataType< ::ropigo::SimpleWriteRequest>
{
  static const char* value()
  {
    return DataType< ::ropigo::SimpleWrite >::value();
  }
  static const char* value(const ::ropigo::SimpleWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ropigo::SimpleWriteResponse> should match 
// service_traits::MD5Sum< ::ropigo::SimpleWrite > 
template<>
struct MD5Sum< ::ropigo::SimpleWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ropigo::SimpleWrite >::value();
  }
  static const char* value(const ::ropigo::SimpleWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ropigo::SimpleWriteResponse> should match 
// service_traits::DataType< ::ropigo::SimpleWrite > 
template<>
struct DataType< ::ropigo::SimpleWriteResponse>
{
  static const char* value()
  {
    return DataType< ::ropigo::SimpleWrite >::value();
  }
  static const char* value(const ::ropigo::SimpleWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROPIGO_MESSAGE_SIMPLEWRITE_H
