// Generated by gencpp from file ropigo/SimpleWriteResponse.msg
// DO NOT EDIT!


#ifndef ROPIGO_MESSAGE_SIMPLEWRITERESPONSE_H
#define ROPIGO_MESSAGE_SIMPLEWRITERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ropigo
{
template <class ContainerAllocator>
struct SimpleWriteResponse_
{
  typedef SimpleWriteResponse_<ContainerAllocator> Type;

  SimpleWriteResponse_()
    : status(0)  {
    }
  SimpleWriteResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::ropigo::SimpleWriteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ropigo::SimpleWriteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleWriteResponse_

typedef ::ropigo::SimpleWriteResponse_<std::allocator<void> > SimpleWriteResponse;

typedef boost::shared_ptr< ::ropigo::SimpleWriteResponse > SimpleWriteResponsePtr;
typedef boost::shared_ptr< ::ropigo::SimpleWriteResponse const> SimpleWriteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ropigo::SimpleWriteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ropigo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ropigo::SimpleWriteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ropigo::SimpleWriteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ropigo::SimpleWriteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::ropigo::SimpleWriteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ropigo/SimpleWriteResponse";
  }

  static const char* value(const ::ropigo::SimpleWriteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n\
\n\
";
  }

  static const char* value(const ::ropigo::SimpleWriteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleWriteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ropigo::SimpleWriteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ropigo::SimpleWriteResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROPIGO_MESSAGE_SIMPLEWRITERESPONSE_H
