#include "enum_functions.hpp"

BEGIN_ENUM(robot_decision_mode_t)
{       
    DECL_ENUM_ELEMENT(LINE_FOLLOWING)    
    DECL_ENUM_ELEMENT(LINE_FOLLOWING_RIGHT_ANGLE)    
    DECL_ENUM_ELEMENT(LINE_ACQUISITION)    
    DECL_ENUM_ELEMENT(DEPTH_SENSING) 
    DECL_ENUM_ELEMENT(DEPTH_FOLLOWING_WALL) 
    DECL_ENUM_ELEMENT(DEPTH_SENSING_WAITING) 
    DECL_ENUM_ELEMENT(ROTATION_AFTER_DEPTH_SENSED_APERTURE) 
    DECL_ENUM_ELEMENT(ROTATION_WAITING_COMPLETION_APERTURE) 
    DECL_ENUM_ELEMENT(ROTATION)
}
END_ENUM